### ISSUE TITLE
Is AsExpandable still necessary on EF Core?

### ISSUE THREAD

**Issue by brunosantosrhsenso** [scottksmith95/LINQKit#100]
When trying to convert a Core 2.2 web app (EF 2.2) to Core 3 (EF 3.0), AsExpandable was throwing an exception "Could not load file System.Interactive.Async". I then removed AsExpandable and the query (using predicatebuilder) seemed to work just fine. I did the same with the Core 2.2 version, and it also seemed to have worked properly. So now I'm wondering if I'm missing some feature by removing AsExpandable or if it's just not necessary anymore.

**Comment by StefH** [comment]
Can you maybe create a example project to demonstrate this?

**Comment by joshmouch** [comment]
I get this, too.

**Comment by 206mph** [comment]
I am running into the same problem with AsExpandable after converting to Net Core 3. As brunosantosrhsenso mentioned, removing AsExpandable works but want to make sure that's correct.

**Comment by StefH** [comment]
If you want to use async. Then you need the LinqKit version which references EF or EFCore.

See the table on main page from this project.

Using Expandable on net core 3 : I have to check...

**Comment by joshmouch** [comment]
@StefH 
You still do need to use it in at least one case that I've found.

**Comment by StefH** [comment]
@joshmouch and @206mph and @brunosantosrhsenso 
New preview is uploaded : `LinqKit 1.1.17-preview-02` which works with EFCore 3.

Please test.

**Comment by mariusAF** [comment]
Preview works - Thanks @StefH

**Comment by StefH** [comment]
`LinqKit 1.1.17-preview-04` is also uploaded to NuGet;
Please test.

**Comment by Armarr** [comment]
Can confirm that preview 04 also works

**Comment by StefH** [comment]
https://github.com/scottksmith95/LINQKit/pull/103

**Comment by Pao-lino** [comment]
Excuse me, I'm on EF Core 5 and installed the LinqKit.Microsoft.EntityFrameworkCore package.
I'm using PredicateBuilder without AsExpandable and it's working.
It's not clear to me if AsExpandable is necessary or not.

**Comment by CesarD** [comment]
> @StefH Excuse me, I'm on EF Core 5 and installed the LinqKit.Microsoft.EntityFrameworkCore package. I'm using PredicateBuilder without AsExpandable and it's working. It's not clear to me if AsExpandable is necessary or not.

Same for me. Doesn't seem to be needed anymore... Is it?

**Comment by ElectroBuddha** [comment]
I can also confirm that PredicateBuilder is working without `.AsExpandable()` in EntityFramework Core 7.

**Comment by n0099** [comment]
I can also confirm that PredicateBuilder is working without .AsExpandable() in EntityFramework Core 8.
