### ISSUE TITLE
Support for EF 6.3, targeting net45 and netstandard2.1

### ISSUE THREAD

**Issue by jtheisen** [scottksmith95/LINQKit#101]
The new version of EntityFramework 6.3 has an additional target, netstandard2.1, allowing it to be used with .NET Core 3.

I would assume that, for LINQKit EF6's incarnation, to support that new target also, it's "only" a package management issue rather than requiring any code changes.

**Comment by StefH** [comment]
Seems reasonable. I will investigate if LinqKit and LinqKit.EntityFramework can also Target netstandard 2.1 + EF 6.3

**Comment by StefH** [comment]
I can upload a preview version to MyGet so that you can test, would that help?

**Comment by jtheisen** [comment]
It's not extremely pressing in my case, but if you give me a link I'll try it out, thanks!

**Comment by ynauls** [comment]
any updates? looking for .netstandard2.1 support

**Comment by jtheisen** [comment]
Btw, I'm not sure if LINQKit.Core needs a new release at all. I think it already has netstandard2.0 as a target. Only the EntityFramework package (LINQKit.EntityFramework) hasn't, and there it needs to be 2.1 as that is the only version of netstandard that the new EF is targeting (for reasons unknown to me).

**Comment by StefH** [comment]
@ynauls 
1.1.17-preview-01 is available for testing at MyGet : https://www.myget.org/F/linqkit/api/v3/index.json

**Comment by ynauls** [comment]
@StefH, I needed this to upgrade to EF 3, I was getting the same error described here [#100 by @brunosantosrhsenso](https://github.com/scottksmith95/LINQKit/issues/100#issue-477886013). Using 1.1.17-preview, I get get past that error, but now I getting the same error described here [#100 by @joshmouch](https://github.com/scottksmith95/LINQKit/issues/100#issuecomment-537195988)

**Comment by StefH** [comment]
I need to update the code because ef3 now supports real async enumerable.

**Comment by StefH** [comment]
@ynauls 
New preview is uploaded : `LinqKit 1.1.17-preview-02` which works with EFCore 3.

Please test.

**Comment by ynauls** [comment]
@StefH, `LinqKit 1.1.17-preview-02` looks good on initial pass. Will keep testing.

**Comment by ynauls** [comment]
@StefH, when can we expect 1.1.17 on NuGet?

**Comment by StefH** [comment]
I'm waiting for verification on this one also:https://github.com/scottksmith95/LINQKit/issues/102

Once that's correct, I'll create a NuGet.

**Comment by StefH** [comment]
https://github.com/scottksmith95/LINQKit/pull/103
