### ISSUE TITLE
System.InvalidOperationException HResult=0x80131509 - See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information

### ISSUE THREAD

**Issue by StefH** [scottksmith95/LINQKit#106]
Related to : 
- https://stackoverflow.com/questions/58092869/ef-core-2-2-linq-query-not-working-in-ef-core-3-0
- https://github.com/scottksmith95/LINQKit/issues/105

**Comment by williamdnapier** [comment]
@StefH I think you may be safe to close this one too.

**Comment by StefH** [comment]
This problem is more generic, like in EF 2.x some code was evaluated at the client but there was no feedback about this.
In EF 3 that same code will throw exception.

**Comment by williamdnapier** [comment]
ok, understood

**Comment by sdanyliv** [comment]
This issue is not related to LINQKit, just close. Such queries are not translatable to the SQL, I have mentioned that in not so popular [SO answer ](https://stackoverflow.com/questions/64377955/linq-to-database-how-to-group-entities-properly-and-groupby-limitations)

**Comment by StefH** [comment]
Moved this to WIKI : https://github.com/scottksmith95/LINQKit/wiki/Client-v.s.-Service-side-evaluation
