### ISSUE TITLE
AsQueryable<Order> ex example app, EF Core 3,  LinqKit 1.1.17-preview-04

### ISSUE THREAD

**Issue by williamdnapier** [scottksmith95/LINQKit#107]
I just grabbed LinqKit.Microsoft.EntityFrameworkCore(1.1.17-preview-04) to try to get around the EF Core 3 .AsExandable(): [LINQKit issue 100](https://github.com/scottksmith95/LINQKit/issues/100)

When I try to run the little example console app:

``` c#
using System;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Linq.Expressions;
using LinqKit;
using Microsoft.EntityFrameworkCore;

public class Order
{
    [Key]
    public int Id { get; set; }
    [Required]
    public int Amount { get; set; }
    [Required]
    public DateTime OrderDate { get; set; }
}
/// <summary> Some simple EF DBContext item for this example</summary>
public class MyDbContext : DbContext
{
    public DbSet<Order> Orders { get; set; }
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
    optionsBuilder.UseSqlServer(@"Server=.\SQLEXPRESS2;Database=MyDatabase;Trusted_Connection=True;");
    }
}

class Program
{
    static void Main(string[] args)
    {
        Expression<Func<IQueryable<Order>, decimal?>> expression =
            orders => orders.Average(o => (decimal?)o.Amount);

        using (var context = new MyDbContext())
        {
            IQueryable<Order> orders = context.Orders;
            var q = from o in orders.AsExpandable()
                    group o by o.OrderDate into g
                    select new
                    {
                        OrderDate = g.Key,
                        AggregatedAmount = expression.Invoke(g.AsQueryable())
                    };
            //ToList or ToListAsync:
            q.ToList().ForEach(Console.WriteLine);
            Console.ReadLine();
        }
    }
}
```

It still throws an exception on this line: 

``` c#
q.ToList().ForEach(Console.WriteLine);
```
			
System.InvalidOperationException
  HResult=0x80131509
  Message=Processing of the LINQ expression 'AsQueryable<Order>(NavigationTreeExpression
    Value: default(IGrouping<DateTime, Order>)
    Expression: (Unhandled parameter: e))' by 'NavigationExpandingExpressionVisitor' failed. This may indicate either a bug or a limitation in EF Core. See https://go.microsoft.com/fwlink/?linkid=2101433 for more detailed information.
  Source=Microsoft.EntityFrameworkCore
  StackTrace:
   at Microsoft.EntityFrameworkCore.Query.Internal.NavigationExpandingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
truncated

Thanks,
Bill

**Comment by StefH** [comment]
I think, you should use:
`Expression<Func<IGrouping<DateTime, Order>, decimal>> expression = orders => orders.Average(o => (decimal)o.Amount);`

See example here: https://github.com/StefH/LinqKitExamples/tree/master/ConsoleAppForTestingEFCore3

(However I did not yet test on real DB)

**Comment by williamdnapier** [comment]
@StefH Yes, rewriting the expression works when using a real database. Thanks.

**Comment by StefH** [comment]
Maybe I need to update the example which is explained in the readme?

**Comment by williamdnapier** [comment]
Probably a good idea.
