### ISSUE TITLE
Restructure dependencies for LinqKit.Microsoft.EntityFrameworkCore for better support EFCore3

### ISSUE THREAD

**Issue by StefH** [scottksmith95/LINQKit#114]
Update dependencies for LinqKit.Microsoft.EntityFrameworkCore for better support EFCore3

Proposal:

| LinqKit Microsoft.EntityFrameworkCore | EF Core version | .NET versions |
| - | - | - |
| 1.1.x | >= 1.1.0 |  .NETFramework 4.5.1 and .NETStandard 1.3 |
| 2.0.1 | >= 2.0.1 | .NETStandard 2.0 |
| 3.0.0 | >= 3.0.0 | .NETStandard 2.1 |
| 3.0.0 | >= 3.1.0 | .NETStandard 2.0 |

**Comment by StefH** [comment]
See also https://github.com/scottksmith95/LINQKit/issues/95

**Comment by alnintex** [comment]
The proposed changes make sense to me, I tested them and [the bug we had faced](https://github.com/scottksmith95/LINQKit/issues/95) is resolved

**Comment by StefH** [comment]
@alnintex Thanks for testing. I'll release a official NuGet for Microsoft.EntityFrameworkCore today or tomorrow.

**Comment by StefH** [comment]
https://github.com/scottksmith95/LINQKit/pull/115
