### ISSUE TITLE
LinqKit fails with Entity Framework Core 5

### ISSUE THREAD

**Issue by btihanyi** [scottksmith95/LINQKit#116]
LinqKit's query expansion functionality does not work with Entity Framework Core 5, well, since the 5.0.0-preview.2.20159.4 to be exact. It throws an exception: 'Unhandled expression type: 'Extension''

I don't know what could be that [Extension expression](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expressiontype?view=netframework-4.0#System_Linq_Expressions_ExpressionType_Extension), but it's been there since .NET Framework 4.0.

Of course, you could handle it in your code, but I suggest you to use the official [ExpressionVisitor](https://docs.microsoft.com/en-us/dotnet/api/system.linq.expressions.expressionvisitor?view=netframework-4.0) class, at least for the newer target frameworks, so it would be future-proof.

**Comment by StefH** [comment]
@btihanyi 
Can you try https://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/5.0.0-preview.1 ?

**Comment by StefH** [comment]
@btihanyi 
Did you have time to test this preview version?

**Comment by btihanyi** [comment]
@StefH
Sorry, I'm currently on my vacation. I will check it next week.

**Comment by btihanyi** [comment]
I've checked it and now it works fine. But I still wonder why don't you just use the official `ExpressionVisitor` class if the target framework is not .NET 3.5? They are doing basically the same. Like I said, it would be future-proof and I haven't found any performance difference between the two.

**Comment by StefH** [comment]
@btihanyi 
Thanks for testing.

Actually I don't know why a custom ExpressionVisitor is used in LinqKit, but for now I keep it like it is.
Maybe add a new issue/PR to just use this custom ExpressionVisitor for .NET 3.5 and use the normal one for all other frameworks.

Other question:
What version should I give to LinqKit.Microsoft.EntityFrameworkCore? 
Just `5.0.0`?
Or keep in line with Microsoft.EntityFrameworkCore, so version `5.0.0-preview.7`?

**Comment by btihanyi** [comment]
From the comment of the class, the custom `ExpressionVisitor` class comes from the [this old blog post](https://docs.microsoft.com/en-us/archive/blogs/mattwar/linq-building-an-iqueryable-provider-part-ii). It's from 2007, even before .NET 3.5 was released, when there was no built-in `ExpressionVisitor` class. I'm going to write a PR and check if there is any real difference in their implementations, but don't think so.

On the second question: I think while you use a preview (alpha, beta, etc.) package, yours should be too. But you don't have to follow their release numbers (apart from the major part), so 5.0.0-preview1, 5.0.0-preview2 is the proper way to go I believe. Then, when it's officially released, try to target that 5.0.0 version as long as possible.
