### ISSUE TITLE
PredicateBuilder failed on EF Core 5.x

### ISSUE THREAD

**Issue by mannok** [scottksmith95/LINQKit#118]
### Steps to reproduce

Please see the codes below
``` C#
public string[] FindAssets()
{
    string[] result;

    using (var ctx = new StockContext())
    {
        var predicate = PredicateBuilder.New<Asset>().Or(asset => asset.Symbol.Contains("TSLA"));

        result = ctx.Assets.AsExpandable()
        .Where(predicate)
        .Select(z => z.Symbol)
        .ToArray();
    }

    return result;
}
```

When the code start exec at `result = `, it throws
```
Exception: Unhandled expression type: 'Extension'
LinqKit.ExpressionVisitor.Visit(Expression exp)
LinqKit.ExpressionVisitor.VisitExpressionList(ReadOnlyCollection<Expression> original)
LinqKit.ExpressionVisitor.VisitMethodCall(MethodCallExpression m)
LinqKit.ExpressionVisitor.Visit(Expression exp)
LinqKit.Extensions.Expand(Expression expr)
LinqKit.ExpandableQueryProvider<T>.System.Linq.IQueryProvider.CreateQuery<TElement>(Expression expression)
System.Linq.Queryable.Where<TSource>(IQueryable<TSource> source, Expression<Func<TSource, bool>> predicate)
```

### Further technical details

EF Core version: 5.0.0-preview.4.20220.10
Database provider: Microsoft.EntityFrameworkCore.SqlServer 5.0.0-preview.4.20220.10
Target framework: netcoreapp3.1
Operating system: Windows 10
IDE: Visual Studio 2019

**Comment by StefH** [comment]
https://github.com/scottksmith95/LINQKit/issues/116

**Comment by StefH** [comment]
@mannok 
Can you try https://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/5.0.0-preview.1 ?

**Comment by mannok** [comment]
> @mannok
> Can you try https://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/5.0.0-preview.1 ?

Yes! I am using this as a workaround at the moment. Will there be an final release for the comparability issue?

**Comment by mannok** [comment]
> @mannok
> Can you try https://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/5.0.0-preview.1 ?

Thank you so much!

**Comment by StefH** [comment]
I'll release **LinqKit.Microsoft.EntityFrameworkCore** version `5.0.0-preview.6` in some time.

(I keep the same preview version as the one which is used by https://www.nuget.org/packages/Microsoft.EntityFrameworkCore/5.0.0-preview.6.20312.4)
