### ISSUE TITLE
Nuget issue on OS with case-sensitive filesystem

### ISSUE THREAD

**Issue by devlux** [scottksmith95/LINQKit#15]
I've installed the nuget package with monodevelop on linux. But afterwards I was not able to use it as the system was not able to find the package. It seems this is due to the case-sensitive nature of the filesystem and that there is some "mismatch" between certain package id references: at some places "Linq" is used and at others "LINQ". After I renamed all "LINQ" snippets (in filenames and file contents) to "Linq" the package worked like a charm... :-)

**Comment by scottksmith95** [comment]
Feel free to submit a pull request. I will gladly accept it.

Thanks

**Comment by Thorium** [comment]
This fix is in the NuGet package of the LinqKit 1.1.3
