### ISSUE TITLE
Nuget-version is not up-to-date

### ISSUE THREAD

**Issue by Thorium** [scottksmith95/LINQKit#16]
Hello,

The Nuget package is over year old. Could it be updated to match this current version?

**Comment by scottksmith95** [comment]
Sure thing. I will attempt to update it tomorrow.

**Comment by scottksmith95** [comment]
The package has been updated. Would you be interested in joining this project as a contributor and help maintain the nuget package?

**Comment by Thorium** [comment]
Thanks!

Yes I could join.

**Comment by scottksmith95** [comment]
I added you as a collaborator here. What is your username on NuGet?

**Comment by Thorium** [comment]
Same as here: Thorium

**Comment by scottksmith95** [comment]
You have been added.
