### ISSUE TITLE
Xml docs for IntelliSense

### ISSUE THREAD

**Issue by jukkamaljanen** [scottksmith95/LINQKit#17]
Totally missing them... Shouldn't be a big thing to add?

**Comment by scottksmith95** [comment]
I will gladly accept a pull request if you want to take this task on.

**Comment by jukkamaljanen** [comment]
I was hoping you could add some summaries since you are the author. I'm not as good in describing LinqKit as you are.

**Comment by scottksmith95** [comment]
I am not the author. I found this code from some samples from a book. I talked to the authors about maintaining it on GitHub and they agreed.

**Comment by Thorium** [comment]
Added XML-comments to package.
05420063b2691c573b46dcd30ca18501296bfa8a
If you have better descriptions, just create PR. :-)
