### ISSUE TITLE
Timestamp in nuget dependencies

### ISSUE THREAD

**Issue by rauhs** [scottksmith95/LINQKit#170]
Hi,

just FYI, the 1.2.1 version on nuget:

https://www.nuget.org/packages/LinqKit.Core

has the "TimeStamp" package as a dependency. I don't think this is needed.
Cheers

**Comment by StefH** [comment]
https://github.com/scottksmith95/LINQKit/pull/171

**Comment by rauhs** [comment]
Thanks! :)
