### ISSUE TITLE
Cannot use async operations with AsExpandable

### ISSUE THREAD

**Issue by Ben555555** [scottksmith95/LINQKit#176]
I have the following query:

```
var transportModels = await dbContext.Transports
                .AsExpandable()
                .Where(transport => transportIds.Contains(transport.Id))
                .Select(TransportModelProjections.GetProjection())
                .ToListAsync(cancellationToken);
```

I get this error:
The source 'IQueryable' doesn't implement 'IAsyncEnumerable<Gts.Domain.Models.Disposition.Transports.TransportModel>'. Only sources that implement 'IAsyncEnumerable' can be used for Entity Framework asynchronous operations.

As far as I understood async operations should be possible with package 'LinqKit.Microsoft.EntityFrameworkCore'.

Am I doing something wrong?

**Comment by Ben555555** [comment]
Ok I was using LinqKit.Core; instead of LinqKit. Problem solved.

**Comment by sdanyliv** [comment]
@Ben555555, you can omit usage of `AsExpandable()` at all.

Just configure `DbContextOptions`
```cs
builder
    .UseSqlServer(connectionString) // or any other provider
    .WithExpressionExpanding();     // enabling LINQKit extension
```
