### ISSUE TITLE
Why so many different versions targeting different versions of .NET?

### ISSUE THREAD

**Issue by SoftCircuits** [scottksmith95/LINQKit#189]
Just wondering why there are so many different versions of *LinqKit.Microsoft.EntityFrameworkCore* for different versions of .NET.

Does this indicate that I'll likely need to get a newer version of LINQKit as new versions of .NET are released?

**Comment by StefH** [comment]
The different NuGets are actually targeting different version from "Microsoft.EntityFrameworkCore".

So if a new version is released from "Microsoft.EntityFrameworkCore", probably a new NuGet will be needed.
