### ISSUE TITLE
Does not support dnxcore50

### ISSUE THREAD

**Issue by ASADeveloper** [scottksmith95/LINQKit#28]
LinqKit doesnot support dnxcore50. Is there any workaround for it without using entity framework 6 ?

**Comment by Thorium** [comment]
Can you try using the .Net 3.5 version which doesn't have the dependency to EF?


----- Alkuperäinen viesti -----
Lähettäjä: "ASADeveloper" <notifications@github.com>
Lähetetty: ‎12.‎1.‎2016 10:15
Vastaanottaja: "scottksmith95/LINQKit" <LINQKit@noreply.github.com>
Aihe: [LINQKit] Does not support dnxcore50 (#28)

LinqKit doesnot support dnxcore50 Is there any workaround for it without using entity framework 6 ?

**Comment by Emyr42** [comment]
The manifest needs to list appropriate target frameworks.
e.g
"dotnet5.0" for class libraries,
"dnxcore50" for applications,

If the manifest doesn't list any targets, this error occurs:

> NU1002	The dependency LinqKit 1.0.0 in project Foobar does not support framework .NETPlatform,Version=v5.4.

(used this code file to crossreference the manifest schema URIs to manifest versions: https://github.com/NuGet/NuGet2/blob/2.8.7/src/Core/Authoring/ManifestSchemaUtility.cs)

LinqKit 1.0.0 is the .Net 3.5 version, using a V1 manifest.
LinqKit 1.1.3.1 has a dependency on EF6.1.3, using a V2 manifest.

You need a V4 manifest to add targets.

**Comment by Thorium** [comment]
Emyr42, thanks for the instructions! If this is something that could be updated to the source repo, could you do also a PR?

**Comment by StefH** [comment]
A version which supports EntityFramework can be found here:
https://www.nuget.org/packages/EntityFramework.LinqKit

A version which supports Microsoft.EntityFrameworkCore can be found here:
https://www.nuget.org/packages/Microsoft.EntityFrameworkCore.LinqKit

Can you please take a look and reply back here or to my fork ?

**Comment by Thorium** [comment]
StefH I can grant you admin rights to Nuget if you want to make a single package with multiple target frameworks like most of the Nuget packages are, insted of a package per architecture...

**Comment by StefH** [comment]
Hello @Thorium ; if you can add me owner permissions to NuGet and this project, that would be great, then I can fix the AppVeyor build + (maybe check the demo + unit-tests) + upload the new NuGet package.

**Comment by Thorium** [comment]
Hello! You are now also admin of the NuGet package. I can approve pull requests but it needs @scottksmith95 to add you to admins of the GitHub project.

My focus is currently on another data access technology (https://github.com/fsprojects/SQLProvider) so I don't have time to help much on LinqKit coding but I can answer to technical questions if any...

I think the majority of users of LinqKit are still in .NET 4.5 enterprise world with EF so be careful to not break that. :-)

**Comment by StefH** [comment]
@scottksmith95 can you please add me as admin from this GitHub project ?

**Comment by scottksmith95** [comment]
@StefH Done

**Comment by StefH** [comment]
@scottksmith95 Thanks.

closing this issue:
See also:
https://github.com/scottksmith95/LINQKit/issues/32
https://github.com/scottksmith95/LINQKit/pull/33
