### ISSUE TITLE
Is it possible to support PCL and will it work with AsyncTableQuery<T> for SQLite queries?

### ISSUE THREAD

**Issue by xplatsolutions** [scottksmith95/LINQKit#32]
I am using [SQLite.Net-PCL](https://github.com/oysteinkrog/SQLite.Net-PCL) and I have this [problem](http://stackoverflow.com/q/37447117/122769).

I see that versions 1.1.0 to 1.1.3.1 have Entity Framework dependency but 1.0.0 has not. Is it possible to use version 1.0.0 for [using-expression-variables-in-subqueries](https://github.com/scottksmith95/LINQKit#using-expression-variables-in-subqueries) and [combining-expressions](https://github.com/scottksmith95/LINQKit#combining-expressions) in a Portable Class Library and will that work fine with AsyncTableQuery<T> queries?

**Comment by StefH** [comment]
Would **.NETPortable,Version=v4.5,Profile=Profile259** or **.NETPortable,Version=v4.0,Profile=Profile328** be enough for you ? (Same as NewtonSoft.Json)

More details about portable can be found here:
http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY

**Comment by StefH** [comment]
Please check this new version uploaded to NuGet https://www.nuget.org/packages/LinqKit/1.1.4

**Comment by StefH** [comment]
@xplatsolutions Any update?

**Comment by xplatsolutions** [comment]
Not really, I didn't use the library but hey maybe I should revisit this in a project.
