### ISSUE TITLE
.NET Core?

### ISSUE THREAD

**Issue by PivotalAnimal** [scottksmith95/LINQKit#34]
Are there any plans to port this to .NET Core?

**Comment by scottksmith95** [comment]
@Thorium or @StefH Can comment on that. I don't have the bandwidth anymore to continue development.

**Comment by StefH** [comment]
Hi @PivotalAnimal, support for .Net Core has been added to this repository. I'll upload the new NuGet packages in a while.

**Comment by StefH** [comment]
Maybe I'll till dotnet rtm is released...

**Comment by StefH** [comment]
New versions uploaded to NuGet:

- https://www.nuget.org/packages/LinqKit/1.1.4
- https://www.nuget.org/packages/LinqKit.Microsoft.EntityFrameworkCore/1.0.1
- https://www.nuget.org/packages/LinqKit.EntityFramework/1.0.1

Please test.

**Comment by StefH** [comment]
Hello @PivotalAnimal, any success testing the latest NuGets ?

**Comment by jcmontes95** [comment]
Hello, why was the 1.0.2 version removed from nuget? I'm currently using the 1.0.1 and having some issues.

**Comment by StefH** [comment]
Please create a new issue with some details why it fails.

**Comment by StefH** [comment]
@jcmontx Any update ? Else I close this issue.

**Comment by jcmontx** [comment]
@StefH sorry for the delay, I can't remember what my issue was but somehow I fixed it, my app has been in production for months now. Thank you anyway!
