### ISSUE TITLE
System.Interactive.Async load failure

### ISSUE THREAD

**Issue by TyBarthel** [scottksmith95/LINQKit#36]
It appears that the LinqKit.Microsoft.EntityFrameworkCore is attempting to load the System.Interactive.Async assembly of version 1.2 from the GAC.  I'm getting a load failure as I have version 3.0 installed in my project as a NuGet package.

Should the LinqKit.Microsoft.EntityFrameworkCore have the System.Interactive.Async as a package dependency instead of referencing the GAC?

=== Pre-bind state information ===
LOG: DisplayName = System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = 
LOG: Initial PrivatePath = NULL
LOG: Dynamic Base = NULL
LOG: Cache Base = NULL
LOG: AppName = 
Calling assembly : LinqKit.Microsoft.EntityFrameworkCore, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: C:\.vshost.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Interactive.Async, Version=1.2.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: GAC Lookup was unsuccessful.
LOG: Attempting download of new URL f/bin/Debug/System.Interactive.Async.DLL.
LOG: Assembly download was successful. Attempting setup of file: \bin\Debug\System.Interactive.Async.dll
LOG: Entering run-from-source setup phase.
LOG: Assembly Name is: System.Interactive.Async, Version=3.0.0.0, Culture=neutral, PublicKeyToken=94bc3704cddfc263
WRN: Comparing the assembly name resulted in the mismatch: Major Version
ERR: The assembly reference did not match the assembly definition found.
ERR: Run-from-source setup phase failed with hr = 0x80131040.
ERR: Failed to complete setup of assembly (hr = 0x80131040). Probing terminated.

**Comment by StefH** [comment]
Can you retry with latest NuGet ?

**Comment by TyBarthel** [comment]
@StefH Looking good!  I think it's working fine now.  Thank you for the quick response!
