### ISSUE TITLE
NuGet binaries not strong named any more

### ISSUE THREAD

**Issue by springy76** [scottksmith95/LINQKit#38]
I also miss any kind of a changelog which would mention this and in general what changed between 1.1.3 and 1.1.6.

**Comment by StefH** [comment]
**Strong named** : I don't know how to do that in the new project.json / .Net Core 1.0 RTM, please advice

**Changelog**:

- 1.1.4 Update to dotnet rc2 and removed dependency on EntityFramework
- 1.1.5 .Net Core 1.0 RTM + Changed dependency from JetBrains.Annotations to fix issues with System.Runtime
- 1.1.6 Removed portable target to fix issues with .Net Core 1.0 RTM when using this project

**Comment by Thorium** [comment]
The key-file is provided `LINQKit\src\LinqKit.Net45\LinqKit.snk` and it was bound by `*.csproj`-file, but you can probably use also the `Properties\AssemblyInfo.cs` file adding the `AssemblyKeyFileAttribute`

**Comment by springy76** [comment]
Personally I'll keep away from .Net Core 1.0 for at least 1-2 years -- Microsoft may call it RTM, I call it public beta test.

AssemblyKeyFileAttribute creates a compiler warning CS1699 since VS2005 -- I wonder why Microsoft added these to UWP at all.

**Comment by StefH** [comment]
I used the original key-file. New NuGet has been created.

ReleaseNotes: https://github.com/scottksmith95/LINQKit/blob/master/ReleaseNotes.txt

Please verify

**Comment by springy76** [comment]
looks good
