### ISSUE TITLE
Sign the library (strong name) for use in projects signed

### ISSUE THREAD

**Issue by Tolitech** [scottksmith95/LINQKit#40]
Is there the possibility of the library to be **signed**? 
If it is not **strongname**, I believe that the people who sign their libraries can not use it.
(like me)

**Comment by StefH** [comment]
This issue applies to LinqKit.Microsoft.EntityFrameworkCore and Linqkit.EntityFramework.

The original Linqkit is signed.

**Comment by Tolitech** [comment]
Yes that's right.
Before I used the LinqKit, though, I'm updating my version and libraries and am getting an error in using LinqKit PredicateBuilder and asynchronous methods.

"System.InvalidOperationException : The source IQueryable doesn't implement IDbAsyncEnumerable..."

So to solve the problem I googled and saw it would have to write myself changes in LinqKit.

I believe that if I upgrade to LinqKit.EntityFramework also solve.
But I can not use it due to not even be signed.

Thank you.

**Comment by StefH** [comment]
If you use .net 4.5.x or 4.6.x and EntityFramework 6.1.3 ; you can indeed use that NuGet package, however it's not signed yet. I'll take a look.

**Comment by StefH** [comment]
New NuGet is uploaded, please test.

**Comment by Tolitech** [comment]
Perfect.
It worked.
thank you so much.

currently my project uses the previous version, linqkit with asp.net mvc 5 and I am currently working for generation projects in asp.net core (.net framework) with entity framework and dapper.

if you have curiosity: 
https://www.youtube.com/watch?v=PzGSslwyTxg
(subtitles)

thank you again.
