### ISSUE TITLE
Unable to restore packages

### ISSUE THREAD

**Issue by kuebelkasten** [scottksmith95/LINQKit#41]
Just cloned the repository into Visual Studio 2015, getting the following messages:

> C:\Program Files\dotnet\dotnet.exe restore "D:\Projects\LINQKit\.vs\restore.dg"
log  : Restoring packages for D:\Projects\LINQKit\src\LinqKit\project.json...
log  : Restoring packages for D:\Projects\LINQKit\tests\LinqKit.Microsoft.EntityFrameworkCore.Tests\project.json...
log  : Restoring packages for D:\Projects\LINQKit\tests\LinqKit.Tests\project.json...
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/Code52/api/v3/FindPackagesById()?id='dotnet-test-xunit''.
log  : Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/Code52/api/v3/FindPackagesById()?id='dotnet-test-xunit''.
log  : Response status code does not indicate success: 404 (Not Found).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/Code52/api/v3/FindPackagesById()?id='dotnet-test-xunit''.
error: Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/Code52/api/v3/FindPackagesById()?id='xunit''.
log  : Response status code does not indicate success: 404 (Not Found).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/Code52/api/v3/FindPackagesById()?id='dotnet-test-xunit''.
error:   Response status code does not indicate success: 404 (Not Found).
log  : Retrying 'FindPackagesByIdAsyncCore' for source 'https://www.myget.org/F/Code52/api/v3/FindPackagesById()?id='xunit''.
log  : Response status code does not indicate success: 404 (Not Found).
error: Failed to retrieve information from remote source 'https://www.myget.org/F/Code52/api/v3/FindPackagesById()?id='xunit''.
error: Response status code does not indicate success: 404 (Not Found).

I have no idea what I am missing here.

Any help would be greatly appreciated.

**Comment by StefH** [comment]
It maybe looks like you have defined some nuget repository paths yourself in vs2015, can you check this?

**Comment by kuebelkasten** [comment]
Indeed, there was a package source pointing to https://www.myget.org/F/Code52/api/v3 and I have no idea where this is from.
Remove it, cloned again and it is working now.

Thanks.
