### ISSUE TITLE
Performance optimization

### ISSUE THREAD

**Issue by Thorium** [scottksmith95/LINQKit#48]
Not all use LinqKit for SQL-generation, some just compiles lambdas on the way and then this is not a problem. But many are not compiling lambdas at all, but transferring to other domains, usually SQL.

So, now that it is also quite powerful to produce big lambdas and not hammer the database for each object one by one, some enterprise applications use LinqKit to produce heavy dynamic SQL. Entity Framework has some optimizations but it's a complex tool and not always as good as you would expect. Usually the SQL-clauses are huge!

I think the LinqKit-produced expression trees can be hugely optimized before transferring them to SQL and this way we would produce better SQL. Smaller and hitting db-indexes better. See for details this: https://thorium.github.io/Linq.Expression.Optimizer/tutorial.html#Anonymous-object-replacement
(With this tool you could avoid typical nested selects inside nested selects.)

For this to work, the lambdas we have to assume that the lambdas that you transfer to the SQL wouldn't have side-effects. So this would be a problem:

```csharp
var res =
   from x in xs
   let y = CallWebService()
   select x+1; // but not y
```

So, now, we could have multiple options, what do you think:

1. Not touch LinqKit, it's ready.
2. Add one more proj-file/package, besides the current ones, something like LinqKit.Optimizer which references this https://thorium.github.io/Linq.Expression.Optimizer (and FSharp.Core) Could be easy win.
3. Duplicate the code from that package to C#. Create tests that everything is working. Maintain the new complex code.

**Comment by StefH** [comment]
This sounds like a good idea and optimization.

Is there a special reason you choose F# ? If it's easy for you to convert it to C#, that would be my personal preference.
Also there should be more unit-tests.
Or
Keep the code in F#, but convert the project into a .NET Core project. I can help with that.
This is needed, else you cannot reference it from the current LinqKit.

About you options:
1. Yes
2. Could be an option, however we need to convert to portable or .net core and add more unit-tests
3. No
4. Rewrite the Linq.Expression.Optimizer project into C# use in in option 2 above.

**Comment by Thorium** [comment]
The reason is that F# is so much more powerful. The whole source code is actually very short, [under 300 lines](https://github.com/Thorium/Linq.Expression.Optimizer/blob/master/src/Linq.Expression.Optimizer/ExpressionOptimizer.fs), but meanwhile it's easy to write all C# concepts in F#, it is not definitely easy to write the same in C#. Pattern matching in some form will come to C# 7 but I bet not anything like this.

Yes, F# works on .NET core. But I haven't used .NET core earlier. What is the correct way to compile it?

I thought that idea of the core is one-for-all, but:
```
.NET Portable Profile 7 (portable-net45+netcore45)
.NET Portable Profile 47 (portable-net45+sl5+netcore45)
.NET Portable Profile 78 (portable-net45+netcore45+wp8)
.NET Portable Profile 259 (portable-net45+netcore45+wpa81+wp8)
MonoAndroid, MonoTouch, Xamarin.iOS (portable-net45+monoandroid10+monotouch10+xamarinios10)
```

**Comment by Thorium** [comment]
Actually I think the whole LinqKit could be written in about 100 lines of F#.

**Comment by Thorium** [comment]
.NET Core support added for the package...

**Comment by StefH** [comment]
I just checked your updated net35 and .netcore project.

Note that the whole idea from .net core project.json is that you only need to define 1 project which includes different frameworks, that's the change I did for LinqKit project.

Also the nuget package can be automatically created which includes all the frameworks you define.
Tonight I'll take a look at you project and see if I can convert it to 1 project.json project.

**Comment by Thorium** [comment]
Thanks! 
I'll kind of like the FAKE build script (build.fsx) support and I make the publish via paket.template, but it's not having total .NET Core support yet.

I have good news and bad news...
The good news is that actually extending LinqKit could be done easily with no external references need to LinqKit. Just adding some static class:
```csharp
    public static class LinqkitExtension
    {
        /// <summary>Place to optimize your queries. </summary>
        public static Func<Expression, Expression> QueryOptimizer = e => e;
    }
```
And then modifying `ExpandableQuery<T>` changing direct calls `expression.Expand()` to something like this:
```csharp
            var expanded = expression.Expand();
            var optimized = LinqkitExtension.QueryOptimizer(expanded);
            //and then use optimized instead of expression.Expand()
```
Now, it's totally up to the user to select his/her favourite nuget packages. Then user just says at somepoint of his/her program:
```csharp
LinqkitExtension.QueryOptimizer = ExpressionOptimizer.visit;
```

Now, the bad news is that LinqKit doesn't actually construct the whole expression (that would be useful for optimization), it just modifies the separate expressions. The whole expression is constructed by the consumer of these expressions (in my case EntityFramework, and actually v6.1.3 is doing quite ok with that). I think there is no easy way to communicate with EntityFramework at all.

**Comment by StefH** [comment]
I lost you while reading the text above, please rephrase and explain.

(e.g. : _The good news is that actually extending LinqKit could be done easily with no external references need to LinqKit_ should be like The good news is that actually extending LinqKit could be done easily with no external references need to **Linq.Expression.Optimizer)** ???

**Comment by Thorium** [comment]
I was thinking that LinqKit could be nice place to do some expression-tree-optimizations.
I was wrong. LinqKit doesn't gather/combine the expressions as final expression, it just modifies the existing ones.

The right level to optimize is the O/R-mapper.

**Comment by Thorium** [comment]
Wow, better than I expected even!!!

**Comment by Thorium** [comment]
@StefH can ypu please release a new version to NuGet?
I don't have all the required components to get all the projects compiling.
Which actually could be good do document, maybe split readme to smaller parts or something.

**Comment by StefH** [comment]
I'll do.

**Comment by Thorium** [comment]
1.1.7.2 is good.

**Comment by Thorium** [comment]
I've heard all this "project.json is killed and dead" from internet, so I'm not sure if I want to migrate to that in new tools. But if it's working in LinqKit well, then...good let it be there.

**Comment by StefH** [comment]
What I understood is that project.json will maybe be still used for the dependencies, but indeed the projects structure will move back to xproj format. However the new tooling from Visual Studio will do this upgrade automatically when the tooling is released.

**Comment by Thorium** [comment]
Great, thanks! I think this can be closed?

**Comment by Thorium** [comment]
How are these EntityFramework versions updated?
If I used 1.0.3 LinqKit, is it now the LinqKit.EntityFramework or LinqKit?

**Comment by StefH** [comment]
Sorry, forgot these.

Both EF NuGets are now also uploaded.
