### ISSUE TITLE
Using the Linq.Expression.Optimizer with LinqKit in an ASP.NET (MVC) Application

### ISSUE THREAD

**Issue by jblacker** [scottksmith95/LINQKit#50]
My apologies in advance if this should be posted elsewhere because it's not an issue/enhancement, but I wanted to test out the optimization package mentioned in the Readme.md file by @Thorium, but wasn't exactly sure where the static initilization call needs to be made.

The readme states:

>make this static call once before executing your queries (e.g. to your app startup or static class constructor)

Can this call be made once within the application's lifecycle by calling it in the `Application_Start()` event in my Global.asax.cs or does it need to be made on a per-request basis in the `Application_BeginRequest()` event?

**Comment by Thorium** [comment]
There is a just released version 1.0.5 of Linq.Expression.Optimizer, I'll recommend to test that. :-)

I'm not ASP.NET guru, but application level, life of the app domain. So Application_Start() should do.

**Comment by jblacker** [comment]
Yep, looks like you're right.  By keeping it in the Application_Start method the generated SQL queries look optimized compared to without it when I have them sent to my trace log viewer.  Thanks!
