### ISSUE TITLE
PCL Compatibility

### ISSUE THREAD

**Issue by mike-rowley** [scottksmith95/LINQKit#57]
LinqKit 1.1.7.3 can be installed in a Profile 7 PCL but 1.1.8 cannot.

Could not install package 'LinqKit 1.1.8'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile7', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by StefH** [comment]
Can you provide a link to your example project?

**Comment by StefH** [comment]
@mike-rowley Any update ?

**Comment by StefH** [comment]
@mike-rowley can you provide an example project ?

**Comment by mike-rowley** [comment]
I abandoned using LinqKit in my project after 2 weeks without any response.
