### ISSUE TITLE
ExpressionVisitor doesn't handle all expression Types

### ISSUE THREAD

**Issue by cg110** [scottksmith95/LINQKit#61]
While looking at the code, I found that resharper warned me that the switch statement in:
Visit

didn't handle:
`ExpressionType.UnaryPlus`
and
`ExpressionType.Power`

Pretty easy to fix as I believe UnaryPlus is Unary and Power is Binary.

(note I've not actually used them, but wanted to make sure the code handled them)

**Comment by StefH** [comment]
Thanks for reporting.

I created new NuGet.
