### ISSUE TITLE
missing licensingUrl node from nuspec in .NET45

### ISSUE THREAD

**Issue by elduddz** [scottksmith95/LINQKit#69]
We are using proget to manage our packages, this looks as the licensingUrl node to see what the licence is, I can see there is a licence.txt file in the repo, but that is not being referenced in the nuspec file?

Cheers,

Luke

**Comment by StefH** [comment]
Related to https://github.com/scottksmith95/LINQKit/issues/67

**Comment by elduddz** [comment]
I realised it might be a bit out of date, I was looking at the nuspec file in the .net45 version which doesn't have a reference pointer for the licenseUrl node.

No big deal really, we have signed it off as ok to use.
