### ISSUE TITLE
selectively apply QueryOptimizer

### ISSUE THREAD

**Issue by springy76** [scottksmith95/LINQKit#70]
I would like to apply the QueryOptimizer only on selected queries instead of only being able to globally turn in on or off.

Reason for that is (currently) that Linq.Expression.Optimizer is introducing massive querytree-recompilation to some of my EF 6.x queries using .AsExpandable().
That means that queries which before only took 900ms for the first run (due to compilation) and then only 2ms for any repeated execution now take 900+ms for every single execution, and memory consumption increases and increases...

Apart from this special problem (which I may be able to solve if I understand how to change that strange F# `ExpressionOptimizer.reductionMethods` thing from C# code) in these days of IOC/DI any `static` thing is considered bad practice.
My "app" is heavily using multi-threading so setting QueryOptimizer on demand is not an option.

**Comment by StefH** [comment]
By design this library is to be used as extension methods.

However, can't you just use the `ExpandableQuery` class ?

**Comment by springy76** [comment]
I'm not sure what I should do with `ExpandableQuery`?

Currently I have a lot of queries which use `.AsExpandable()` because `someExpression.Invoke()` is being used inside the query.
But I have no way to opt out of the call to QueryOptimizer, or ideally only opt-in for specific queries.

What do a `.AsExpandable(Func<Expression,Expression> customOptimizer)` overload any harm?

The only line where QueryOptimizer is being used is this one [src](https://github.com/scottksmith95/LINQKit/blob/08719589c51e5575d3e3288925d3d8f65e29074a/src/LinqKit.Core/ExpandableQuery.cs#L127) which is a private detail, so I don't see how I could change anything by myself.

**Comment by StefH** [comment]
If the `ExpandableQuery` was made public, would that help?

**Comment by springy76** [comment]
I can't see how this would help at all.

I prepared an incomplete proposal (could be a pull request if I could get this entire thing to compile [1]) which shows what I mean:
[https://github.com/springy76/LINQKit/commit/7536c961be3b5bafc49517001d77d3d29590ae68](proposal)

This way I could set the global QueryOptimizer or leave it "null". And for each query I could decide to a) use the global default b) use as special optimizer or c) use no optimizer (by passing null).

**Comment by StefH** [comment]
Ah I see. Sorry I did not get it.

I'll take a look...

**Comment by StefH** [comment]
See this branch : https://github.com/scottksmith95/LINQKit/tree/optimizer which I think includes your requested logic.

**Comment by springy76** [comment]
From the diff it looks good. (I didn't have a clue what to do on the expression tree side.)

**Comment by StefH** [comment]
I did upload new packages to MyGet feed : https://www.myget.org/F/linqkit/api/v3/index.json can you test if this works for you?

**Comment by StefH** [comment]
Did you have time to test this NuGet ?

**Comment by springy76** [comment]
I did a quick test in LINQPad and did not find any problems so far.

**Comment by StefH** [comment]
OK. Version uploaded to NuGet.

I will also try to update the documentation
