### ISSUE TITLE
Documentation Request For Different Versions of LINQKit

### ISSUE THREAD

**Issue by me245** [scottksmith95/LINQKit#73]
I see marked at the top of the ReadMe there are references to the different Projects (and associated NuGet Packages) that are associated with LINQKit. I am curious as to what exactly are the differences between these packages. I do see that they have listed what .Net frameworks these are capable of running against as well as on the NuGet pages for each it specifies what is implemented/missing in that particular package.

As a Newbie to this project I am still left with questions after my initial steps in researching. I want to use it for one or more projects but don't have a large amount of time to do manual testing to make sure I understand the implications of what it says that it is missing, or what exactly I am getting for each package. To clarify with examples of specific questions that I have, consider the following:

+ If I install the LinqKit.Microsoft.EntityFrameworkCore package, does this mean that I am now able to do calls such as AsExpandable(), Expand(), PredicateBuilder(), etc, without any additional packages (aside from the obvious EntityFrameworkCore Dependency) on the supported frameworks? I think this is the case, but making it more clear (either here or on the NuGet site) would be helpful when people are researching the project.  
+ What does it mean when I am missing out on Include(...), IAsync, and IDbAsync support? I know that Include(...) is typically used for making sure Navigation Properties are included in EF for queries against other Tables, is this referring to the same extension method? And what does that imply for when I am no longer able to take advantage of LINQKit? And should the sentence be read as "Is not **_yet_** supported" or as "**Will _never_** be supported"? Or at what point am I no longer able to `await` an `async` function (I can test this with the compiler, but lack the time to investigate at the current moment) and what are some implications of that to consider before investing in using LINQKit as an acceptable part of a solution?  
+ What all are the public extension methods provided by LINQKit? I know that I am awfully spoiled by MSDN API Browser and don't expect that level of documentation, but it would be nice to see without installing a package or poking through all of the source code to know what is available to me as well as the function signatures. It may help clarify the examples already given in the ReadMe as to when I need to call one function versus the other.  

Perhaps I am looking in the wrong place for better clarification, but as of right now I am not seeing it easily. Making it more easily grokked makes the whole project more accessible to more developers and increases the project's exposure making this kind of documentation a helpful thing to have.

**Comment by StefH** [comment]
The `LinqKit` is the original project which can only work for NET 4.5 and EntityFramework (6.x). Note that the `LinqKit.EntityFramework` project has the same functionality but follows the correct naming-convention.

When dotnet core was released, I decided to make a version for dotnet core without any dependencies on entity framework. This is the `LinqKit.Core` version. However you can only use this in case you don't use any version of the EntityFramework.


The `LinqKit.Microsoft.EntityFrameworkCore` version should be used for the new EF 2.x version. So you can indeed use the IAsync, and IDbAsync functionality in a fully supported way.

All extension methods are defined in https://github.com/scottksmith95/LINQKit/blob/master/src/LinqKit.Core/Extensions.cs

I hope this helps, else please indicate what you are missing or do a proposal for a PR to update the readme.

**Comment by springy76** [comment]
I'm using EF6 (with System.Data.SQLite as provider) and can switch between LinqKit.Core and LinqKit without experiencing any difference. Now I'm confused.

**Comment by StefH** [comment]
Did you also try the `Async` methods ? I expect those to fail when just using `LinqKit.Core`.

**Comment by springy76** [comment]
Since using System.Data.SQLite all async methods are blocking I don't use any of them.

**Comment by StefH** [comment]
closing...
