### ISSUE TITLE
Regression: ExpandableQuery<T> is inaccessible due to its protection level

### ISSUE THREAD

**Issue by MatejQ** [scottksmith95/LINQKit#76]
Hello,
when trying to update linqkit from 1.1.9 to 1.1.13, I am getting this error: ExpandableQuery<T> is inaccessible due to its protection level
We need to access this type to test an IQueryable<T> whether it is a database query or not, such as:

`bool isDbQuery = query is System.Data.Entity.Infrastructure.DbQuery<TEntity> || query is LinqKit.ExpandableQuery<TEntity>;`

But type ExpandableQuery<T> was made internal in some of the latest releases. Why? How to overcome this?

**Comment by StefH** [comment]
If you depend on this class, I will create a new NuGet.

**Comment by MatejQ** [comment]
Thanks. It's enough to fix this in a next version.

**Comment by StefH** [comment]
New NuGet will be uploaded in some time.

**Comment by MatejQ** [comment]
I tried version 1.1.14 again, but ExpandableQuery<T> is still internal.

![capture](https://user-images.githubusercontent.com/14346231/36472542-0a2dd2ba-16ea-11e8-94aa-b2cdfe47466c.PNG)

**Comment by StefH** [comment]
Sorry, I'll fix it again.

**Comment by StefH** [comment]
Version 1.1.15 will be uploaded soon.
