### ISSUE TITLE
Reference Linqkit.Core and LinqKit.Microsoft.EntityFrameworkCore  in 1 solution

### ISSUE THREAD

**Issue by vertonghenb** [scottksmith95/LINQKit#79]
Having issues when using the LinqKit.Core in Core project and LinqKit.Microsoft.EntityFrameworkCore in data project
Error CS0433: The type 'LinqKitExtension' exists in both 'LinqKit.Core, Version=1.1.15.0, Culture=neutral, PublicKeyToken=bc217f8844052a91' and 'LinqKit.Microsoft.EntityFrameworkCore, Version=1.1.15.0, Culture=neutral, PublicKeyToken=a5e68054d5e7f94b' (CS0433) (Vault.Web)

**Comment by StefH** [comment]
I can understand this issue, the code is the same.

Can you maybe just use the `LinqKit.Microsoft.EntityFrameworkCore` in all projects?

**Comment by vertonghenb** [comment]
Well, I'm using it in the domain layer so using `LinqKit.Microsoft.EntityFrameworkCore` would take a dependency of `Microsoft.EntityFrameworkCore` on the domain which isn't really what i'd want. I'm just using `LinqKit`  in Data and the Domain which solved the issue appearantly.
