### ISSUE TITLE
Refactor to segregate EntityFramework dependencies

### ISSUE THREAD

**Issue by Serenyrddraig** [scottksmith95/LINQKit#8]
I have found this project extremely useful. However, I was unable to use the nuget package because of the way that the dependencies are packaged. 

I'm integrating into an SOA product with very strict rules, in particular data access dependencies may not occur in a business service, only in a data service. To solve this issue, I cloned your repository and divided it into two assemblies LinqKit and LinqKit.EntityFramework. This solved my issue, and others may have the same requirement. I would suggest this to be your default, and update the nuget package accordingly.

**Comment by scottksmith95** [comment]
Closing as no response
