### ISSUE TITLE
Change namespace of LinqKit.Microsoft.EntityFrameworkCore

### ISSUE THREAD

**Issue by vertonghenb** [scottksmith95/LINQKit#81]
I want to be able to use LinqKit.Core in my domain project and Linqkit.EntityFramework.Core in my data project(since I don't want a dependency on EF Core in my domain). However my data layer has a dependency on the domain project therefore I cannot use LinqKit's functions since the calls are ambigious.

Steps to reproduce:
Reference Linqkit.Core in your domain layer (you don't want a EF dependency here)
and LinqKit.Microsoft.EntityFrameworkCore in the data layer.

Please rename the namespaces of the LinqKit.EntityFramework.Core project, so we can have some separation.

**Comment by StefH** [comment]
If the domain project is also used by other applications which _don't_ use Entity Framework, it makes sense.

However if the domain project is always used in applications which are using Entity Framework, it has no use to make a separation.

**Comment by vertonghenb** [comment]
The domain project is also used by other applications which don't use Entity Framework.

**Comment by StefH** [comment]
A solution would be to conditionally include the correct library in the domain project.
Example could be:
``` xml
<ItemGroup Condition="'$(LibraryType)' == 'EF'">
    <PackageReference Include="LinqKit.Core" Version="1.1.15" />
  </ItemGroup>

  <ItemGroup Condition="'$(LibraryType)' != 'EF'">
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="1.1.15" />
  </ItemGroup>
```

Where you define `EF` or `non-EF` in the project where the domain project is used.
